//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTraveller.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTraveller.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uTraveler.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Common_Total {
            get {
                return ResourceManager.GetString("Common_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string EventDetails_AddPhoto_Button {
            get {
                return ResourceManager.GetString("EventDetails_AddPhoto_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string EventDetails_Camera_Button {
            get {
                return ResourceManager.GetString("EventDetails_Camera_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        public static string EventDetails_Photo {
            get {
                return ResourceManager.GetString("EventDetails_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string EventDetails_Photos {
            get {
                return ResourceManager.GetString("EventDetails_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Current.
        /// </summary>
        public static string EventItem_MenuItem_SetCurrent {
            get {
                return ResourceManager.GetString("EventItem_MenuItem_SetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset as Current.
        /// </summary>
        public static string EventItem_MenuItem_UnsetCurrent {
            get {
                return ResourceManager.GetString("EventItem_MenuItem_UnsetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Facebook_Post_Albums {
            get {
                return ResourceManager.GetString("Facebook_Post_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Facebook_Post_Comment {
            get {
                return ResourceManager.GetString("Facebook_Post_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Facebook_Post_Privacy {
            get {
                return ResourceManager.GetString("Facebook_Post_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Facebook_Privacy_ALL_FRIENDS {
            get {
                return ResourceManager.GetString("Facebook_Privacy_ALL_FRIENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string Facebook_Privacy_EVERYONE {
            get {
                return ResourceManager.GetString("Facebook_Privacy_EVERYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Facebook_Privacy_SELF {
            get {
                return ResourceManager.GetString("Facebook_Privacy_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, d MMMM yyyy, HH:mm.
        /// </summary>
        public static string Full_Date_Format {
            get {
                return ResourceManager.GetString("Full_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the limit for {0} and can&apos;t add more than {1}.
        /// </summary>
        public static string Limit_Exceeded {
            get {
                return ResourceManager.GetString("Limit_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Message_Post_Button {
            get {
                return ResourceManager.GetString("Message_Post_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Message_Update_Button {
            get {
                return ResourceManager.GetString("Message_Update_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Spendings.
        /// </summary>
        public static string MoneySpendings {
            get {
                return ResourceManager.GetString("MoneySpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have internet connection to sign in :(.
        /// </summary>
        public static string No_Connection_To_Sign_In {
            get {
                return ResourceManager.GetString("No_Connection_To_Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have internet connection to sign up :(.
        /// </summary>
        public static string No_Connection_To_SignUp {
            get {
                return ResourceManager.GetString("No_Connection_To_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t crop the image because it&apos;s not a JPEG file or has a bad format.
        /// </summary>
        public static string PhotoCrop_Wrong_Extension {
            get {
                return ResourceManager.GetString("PhotoCrop_Wrong_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check-in.
        /// </summary>
        public static string PlanItem_CheckIn {
            get {
                return ResourceManager.GetString("PlanItem_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check-out.
        /// </summary>
        public static string PlanItem_CheckOut {
            get {
                return ResourceManager.GetString("PlanItem_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undated.
        /// </summary>
        public static string PlanItem_Undated {
            get {
                return ResourceManager.GetString("PlanItem_Undated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amuzement Park.
        /// </summary>
        public static string PlanItemType_AmuzementPark {
            get {
                return ResourceManager.GetString("PlanItemType_AmuzementPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        public static string PlanItemType_ATM {
            get {
                return ResourceManager.GetString("PlanItemType_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string PlanItemType_Bank {
            get {
                return ResourceManager.GetString("PlanItemType_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        public static string PlanItemType_Beach {
            get {
                return ResourceManager.GetString("PlanItemType_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicycle.
        /// </summary>
        public static string PlanItemType_Bicycle {
            get {
                return ResourceManager.GetString("PlanItemType_Bicycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string PlanItemType_Bus {
            get {
                return ResourceManager.GetString("PlanItemType_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        public static string PlanItemType_Cafe {
            get {
                return ResourceManager.GetString("PlanItemType_Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string PlanItemType_Camping {
            get {
                return ResourceManager.GetString("PlanItemType_Camping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rent.
        /// </summary>
        public static string PlanItemType_Car {
            get {
                return ResourceManager.GetString("PlanItemType_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        public static string PlanItemType_Church {
            get {
                return ResourceManager.GetString("PlanItemType_Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema.
        /// </summary>
        public static string PlanItemType_Cinema {
            get {
                return ResourceManager.GetString("PlanItemType_Cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string PlanItemType_Club {
            get {
                return ResourceManager.GetString("PlanItemType_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert.
        /// </summary>
        public static string PlanItemType_Concert {
            get {
                return ResourceManager.GetString("PlanItemType_Concert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string PlanItemType_Entertainment {
            get {
                return ResourceManager.GetString("PlanItemType_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferry.
        /// </summary>
        public static string PlanItemType_Ferry {
            get {
                return ResourceManager.GetString("PlanItemType_Ferry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string PlanItemType_Flight {
            get {
                return ResourceManager.GetString("PlanItemType_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string PlanItemType_Hotel {
            get {
                return ResourceManager.GetString("PlanItemType_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string PlanItemType_House {
            get {
                return ResourceManager.GetString("PlanItemType_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string PlanItemType_Library {
            get {
                return ResourceManager.GetString("PlanItemType_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string PlanItemType_Market {
            get {
                return ResourceManager.GetString("PlanItemType_Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string PlanItemType_Meeting {
            get {
                return ResourceManager.GetString("PlanItemType_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string PlanItemType_Motorcycle {
            get {
                return ResourceManager.GetString("PlanItemType_Motorcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string PlanItemType_Museum {
            get {
                return ResourceManager.GetString("PlanItemType_Museum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string PlanItemType_Other {
            get {
                return ResourceManager.GetString("PlanItemType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string PlanItemType_Park {
            get {
                return ResourceManager.GetString("PlanItemType_Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string PlanItemType_Parking {
            get {
                return ResourceManager.GetString("PlanItemType_Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string PlanItemType_Petrol {
            get {
                return ResourceManager.GetString("PlanItemType_Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string PlanItemType_Pool {
            get {
                return ResourceManager.GetString("PlanItemType_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pub.
        /// </summary>
        public static string PlanItemType_Pub {
            get {
                return ResourceManager.GetString("PlanItemType_Pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string PlanItemType_Restaurant {
            get {
                return ResourceManager.GetString("PlanItemType_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string PlanItemType_Ship {
            get {
                return ResourceManager.GetString("PlanItemType_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string PlanItemType_Shopping {
            get {
                return ResourceManager.GetString("PlanItemType_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showplace.
        /// </summary>
        public static string PlanItemType_Showplace {
            get {
                return ResourceManager.GetString("PlanItemType_Showplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium.
        /// </summary>
        public static string PlanItemType_Stadium {
            get {
                return ResourceManager.GetString("PlanItemType_Stadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string PlanItemType_Taxi {
            get {
                return ResourceManager.GetString("PlanItemType_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theatre.
        /// </summary>
        public static string PlanItemType_Theatre {
            get {
                return ResourceManager.GetString("PlanItemType_Theatre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train.
        /// </summary>
        public static string PlanItemType_Train {
            get {
                return ResourceManager.GetString("PlanItemType_Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoo.
        /// </summary>
        public static string PlanItemType_Zoo {
            get {
                return ResourceManager.GetString("PlanItemType_Zoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Route_Select {
            get {
                return ResourceManager.GetString("Route_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect.
        /// </summary>
        public static string Route_Unselect {
            get {
                return ResourceManager.GetString("Route_Unselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy.
        /// </summary>
        public static string Short_Dayly_Date_Format {
            get {
                return ResourceManager.GetString("Short_Dayly_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy, HH:mm.
        /// </summary>
        public static string Short_No_Week_Name_Date_Format {
            get {
                return ResourceManager.GetString("Short_No_Week_Name_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send email to reset password. Please, try agail later or contact us: utraveler_helpdesk@yahoo.com.
        /// </summary>
        public static string SignIn_Request_Reset_Password_Fail {
            get {
                return ResourceManager.GetString("SignIn_Request_Reset_Password_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a request to reset password....
        /// </summary>
        public static string SignIn_Request_Reset_Password_Progress {
            get {
                return ResourceManager.GetString("SignIn_Request_Reset_Password_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code to reset the password has been sent to the indicated email. It may take about 5 min..
        /// </summary>
        public static string SignIn_Request_Reset_Password_Success {
            get {
                return ResourceManager.GetString("SignIn_Request_Reset_Password_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been signed in successfully :).
        /// </summary>
        public static string SignIn_Success {
            get {
                return ResourceManager.GetString("SignIn_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign in user because of unexpected error. Please, try again later..
        /// </summary>
        public static string SignIn_Unexpected_Error {
            get {
                return ResourceManager.GetString("SignIn_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign in user. Error: {0} :(.
        /// </summary>
        public static string SignIn_UnexpectedServer_Error {
            get {
                return ResourceManager.GetString("SignIn_UnexpectedServer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin in user....
        /// </summary>
        public static string SigningIn_User {
            get {
                return ResourceManager.GetString("SigningIn_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this E-mail already exists :(.
        /// </summary>
        public static string SignUp_Email_Exist {
            get {
                return ResourceManager.GetString("SignUp_Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your Facebook profile....
        /// </summary>
        public static string SignUp_Facebook_Get_Profile_Progress {
            get {
                return ResourceManager.GetString("SignUp_Facebook_Get_Profile_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t register user because of internal server error. Please, try again later..
        /// </summary>
        public static string SignUp_Fail {
            get {
                return ResourceManager.GetString("SignUp_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail must have more than 6 symbols.
        /// </summary>
        public static string SignUp_Incorrect_Email {
            get {
                return ResourceManager.GetString("SignUp_Incorrect_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have more than 3 symbols.
        /// </summary>
        public static string SignUp_Incorrect_Password {
            get {
                return ResourceManager.GetString("SignUp_Incorrect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not matched.
        /// </summary>
        public static string SignUp_Password_Not_Matched {
            get {
                return ResourceManager.GetString("SignUp_Password_Not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing up User with e-mail: {0}.
        /// </summary>
        public static string SignUp_Progress {
            get {
                return ResourceManager.GetString("SignUp_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been registered successfully and you can start using the App :).
        /// </summary>
        public static string SignUp_Success {
            get {
                return ResourceManager.GetString("SignUp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t register an user. Error: &apos;{0}&apos; :(.
        /// </summary>
        public static string SignUp_Unexpected_Error {
            get {
                return ResourceManager.GetString("SignUp_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spendings.
        /// </summary>
        public static string Spendings_Button {
            get {
                return ResourceManager.GetString("Spendings_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping.
        /// </summary>
        public static string Spendings_Category_Camping {
            get {
                return ResourceManager.GetString("Spendings_Category_Camping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Spendings_Category_Club {
            get {
                return ResourceManager.GetString("Spendings_Category_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert.
        /// </summary>
        public static string Spendings_Category_Concert {
            get {
                return ResourceManager.GetString("Spendings_Category_Concert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Spendings_Category_Entertainment {
            get {
                return ResourceManager.GetString("Spendings_Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastFood.
        /// </summary>
        public static string Spendings_Category_FastFood {
            get {
                return ResourceManager.GetString("Spendings_Category_FastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string Spendings_Category_Fine {
            get {
                return ResourceManager.GetString("Spendings_Category_Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string Spendings_Category_Fuel {
            get {
                return ResourceManager.GetString("Spendings_Category_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery.
        /// </summary>
        public static string Spendings_Category_Grocery {
            get {
                return ResourceManager.GetString("Spendings_Category_Grocery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Spendings_Category_Hotel {
            get {
                return ResourceManager.GetString("Spendings_Category_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string Spendings_Category_House {
            get {
                return ResourceManager.GetString("Spendings_Category_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Spendings_Category_Internet {
            get {
                return ResourceManager.GetString("Spendings_Category_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        public static string Spendings_Category_Museum {
            get {
                return ResourceManager.GetString("Spendings_Category_Museum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Spendings_Category_Other {
            get {
                return ResourceManager.GetString("Spendings_Category_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string Spendings_Category_Parking {
            get {
                return ResourceManager.GetString("Spendings_Category_Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Spendings_Category_Phone {
            get {
                return ResourceManager.GetString("Spendings_Category_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pub.
        /// </summary>
        public static string Spendings_Category_Pub {
            get {
                return ResourceManager.GetString("Spendings_Category_Pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public transport.
        /// </summary>
        public static string Spendings_Category_PublicTransport {
            get {
                return ResourceManager.GetString("Spendings_Category_PublicTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string Spendings_Category_Restaurant {
            get {
                return ResourceManager.GetString("Spendings_Category_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string Spendings_Category_Shopping {
            get {
                return ResourceManager.GetString("Spendings_Category_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showplace.
        /// </summary>
        public static string Spendings_Category_Showplace {
            get {
                return ResourceManager.GetString("Spendings_Category_Showplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souvenir.
        /// </summary>
        public static string Spendings_Category_Souvenir {
            get {
                return ResourceManager.GetString("Spendings_Category_Souvenir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport rent.
        /// </summary>
        public static string Spendings_Category_TransportRent {
            get {
                return ResourceManager.GetString("Spendings_Category_TransportRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dram (Armenia).
        /// </summary>
        public static string Spendings_Currency_ARDram {
            get {
                return ResourceManager.GetString("Spendings_Currency_ARDram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar (Australia).
        /// </summary>
        public static string Spendings_Currency_AUDollar {
            get {
                return ResourceManager.GetString("Spendings_Currency_AUDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manat (Azerbaijan).
        /// </summary>
        public static string Spendings_Currency_AZManat {
            get {
                return ResourceManager.GetString("Spendings_Currency_AZManat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lev (Bulgaria).
        /// </summary>
        public static string Spendings_Currency_BULev {
            get {
                return ResourceManager.GetString("Spendings_Currency_BULev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar (Canada).
        /// </summary>
        public static string Spendings_Currency_CADollar {
            get {
                return ResourceManager.GetString("Spendings_Currency_CADollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frank (Switzerland).
        /// </summary>
        public static string Spendings_Currency_CHFrank {
            get {
                return ResourceManager.GetString("Spendings_Currency_CHFrank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuan (China).
        /// </summary>
        public static string Spendings_Currency_CNYuan {
            get {
                return ResourceManager.GetString("Spendings_Currency_CNYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koruna (Czech Rep.).
        /// </summary>
        public static string Spendings_Currency_CZKoruna {
            get {
                return ResourceManager.GetString("Spendings_Currency_CZKoruna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krona (Denmark).
        /// </summary>
        public static string Spendings_Currency_DNKrona {
            get {
                return ResourceManager.GetString("Spendings_Currency_DNKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro.
        /// </summary>
        public static string Spendings_Currency_Euro {
            get {
                return ResourceManager.GetString("Spendings_Currency_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forint (Hungary).
        /// </summary>
        public static string Spendings_Currency_HUForint {
            get {
                return ResourceManager.GetString("Spendings_Currency_HUForint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krona (Iceland).
        /// </summary>
        public static string Spendings_Currency_ICKrona {
            get {
                return ResourceManager.GetString("Spendings_Currency_ICKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rupee (India).
        /// </summary>
        public static string Spendings_Currency_INRupee {
            get {
                return ResourceManager.GetString("Spendings_Currency_INRupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shekel (Israel).
        /// </summary>
        public static string Spendings_Currency_ISShekel {
            get {
                return ResourceManager.GetString("Spendings_Currency_ISShekel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yen (Japan).
        /// </summary>
        public static string Spendings_Currency_JPYen {
            get {
                return ResourceManager.GetString("Spendings_Currency_JPYen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won (Korea).
        /// </summary>
        public static string Spendings_Currency_KOWon {
            get {
                return ResourceManager.GetString("Spendings_Currency_KOWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lei (Moldova).
        /// </summary>
        public static string Spendings_Currency_MDLei {
            get {
                return ResourceManager.GetString("Spendings_Currency_MDLei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denar (Makedonia).
        /// </summary>
        public static string Spendings_Currency_MKDenar {
            get {
                return ResourceManager.GetString("Spendings_Currency_MKDenar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krona (Norway).
        /// </summary>
        public static string Spendings_Currency_NRKrona {
            get {
                return ResourceManager.GetString("Spendings_Currency_NRKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zloty (Poland).
        /// </summary>
        public static string Spendings_Currency_PLZloty {
            get {
                return ResourceManager.GetString("Spendings_Currency_PLZloty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lei (Romania).
        /// </summary>
        public static string Spendings_Currency_ROLei {
            get {
                return ResourceManager.GetString("Spendings_Currency_ROLei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruble (Russia).
        /// </summary>
        public static string Spendings_Currency_RURuble {
            get {
                return ResourceManager.GetString("Spendings_Currency_RURuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krona (Sweden).
        /// </summary>
        public static string Spendings_Currency_SWKrona {
            get {
                return ResourceManager.GetString("Spendings_Currency_SWKrona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lira (Turkey).
        /// </summary>
        public static string Spendings_Currency_TRLira {
            get {
                return ResourceManager.GetString("Spendings_Currency_TRLira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirham (UAE).
        /// </summary>
        public static string Spendings_Currency_UAEDirham {
            get {
                return ResourceManager.GetString("Spendings_Currency_UAEDirham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hryvnia (Ukraine).
        /// </summary>
        public static string Spendings_Currency_UAHryvnia {
            get {
                return ResourceManager.GetString("Spendings_Currency_UAHryvnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound (UK).
        /// </summary>
        public static string Spendings_Currency_UKPound {
            get {
                return ResourceManager.GetString("Spendings_Currency_UKPound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar (USA).
        /// </summary>
        public static string Spendings_Currency_USDollar {
            get {
                return ResourceManager.GetString("Spendings_Currency_USDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Spendings_Field_Amount {
            get {
                return ResourceManager.GetString("Spendings_Field_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Spendings_Field_Category {
            get {
                return ResourceManager.GetString("Spendings_Field_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Spendings_Field_Date {
            get {
                return ResourceManager.GetString("Spendings_Field_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Spendings_Field_Description {
            get {
                return ResourceManager.GetString("Spendings_Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Spendings_Field_Time {
            get {
                return ResourceManager.GetString("Spendings_Field_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose category.
        /// </summary>
        public static string Spendings_Header_Category {
            get {
                return ResourceManager.GetString("Spendings_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose currency.
        /// </summary>
        public static string Spendings_Header_Currency {
            get {
                return ResourceManager.GetString("Spendings_Header_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some items were not synchronized. Please, try again later :(.
        /// </summary>
        public static string Sync_Fail {
            get {
                return ResourceManager.GetString("Sync_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t synchronize {0} because you have reached the limit and can&apos;t add more than {1}.
        /// </summary>
        public static string Sync_Limit_Exceeded {
            get {
                return ResourceManager.GetString("Sync_Limit_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the Cloud :(.
        /// </summary>
        public static string Sync_Not_Connected {
            get {
                return ResourceManager.GetString("Sync_Not_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization was completed successfully :).
        /// </summary>
        public static string Sync_Success {
            get {
                return ResourceManager.GetString("Sync_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing {0} ....
        /// </summary>
        public static string Sync_Synchronizing_Progress {
            get {
                return ResourceManager.GetString("Sync_Synchronizing_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string Time_Date_Format {
            get {
                return ResourceManager.GetString("Time_Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Plan.
        /// </summary>
        public static string TripPlan {
            get {
                return ResourceManager.GetString("TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot sign in user. Wrong E-mail or Password :(.
        /// </summary>
        public static string Wrong_Email_Or_Password {
            get {
                return ResourceManager.GetString("Wrong_Email_Or_Password", resourceCulture);
            }
        }
    }
}
