//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceImpl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceImpl.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pushpin {
            get {
                object obj = ResourceManager.GetObject("pushpin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/event-rest/me/events/insert?access_token={0}.
        /// </summary>
        internal static string REST_Add_Event {
            get {
                return ResourceManager.GetString("REST_Add_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/message-rest/me/events/{0}/messages/insert?access_token={1}.
        /// </summary>
        internal static string REST_Add_Message {
            get {
                return ResourceManager.GetString("REST_Add_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/spending-rest/me/events/{0}/moneyspending/insert?access_token={1}.
        /// </summary>
        internal static string REST_Add_MoneySpending {
            get {
                return ResourceManager.GetString("REST_Add_MoneySpending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/photo-rest/me/events/{0}/photos/insert?access_token={1}.
        /// </summary>
        internal static string REST_Add_Photo {
            get {
                return ResourceManager.GetString("REST_Add_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/route-rest/me/events/{0}/routes/insert?access_token={1}.
        /// </summary>
        internal static string REST_Add_Route {
            get {
                return ResourceManager.GetString("REST_Add_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/trip-plan-rest/me/events/{0}/trip-plan/insert?access_token={1}.
        /// </summary>
        internal static string REST_Add_TripPlan {
            get {
                return ResourceManager.GetString("REST_Add_TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/event-rest/me/events/{0}/delete?access_token={1}.
        /// </summary>
        internal static string REST_Delete_Event {
            get {
                return ResourceManager.GetString("REST_Delete_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/message-rest/me/events/{0}/messages/{1}/delete?access_token={2}.
        /// </summary>
        internal static string REST_Delete_Message {
            get {
                return ResourceManager.GetString("REST_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/spending-rest/me/events/{0}/moneyspendings/{1}/delete?access_token={2}.
        /// </summary>
        internal static string REST_Delete_MoneySpending {
            get {
                return ResourceManager.GetString("REST_Delete_MoneySpending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/photo-rest/me/events/{0}/photos/{1}/delete?access_token={2}.
        /// </summary>
        internal static string REST_Delete_Photo {
            get {
                return ResourceManager.GetString("REST_Delete_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/route-rest/me/events/{0}/routes/{1}/delete?access_token={2}.
        /// </summary>
        internal static string REST_Delete_Route {
            get {
                return ResourceManager.GetString("REST_Delete_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/trip-plan-rest/me/events/{0}/trip-plan/delete?access_token={1}.
        /// </summary>
        internal static string REST_Delete_TripPlan {
            get {
                return ResourceManager.GetString("REST_Delete_TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/app-settings-rest/get.
        /// </summary>
        internal static string REST_Get_AppInfo {
            get {
                return ResourceManager.GetString("REST_Get_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/event-rest/me/events/{0}?access_token={1}.
        /// </summary>
        internal static string REST_Get_Event {
            get {
                return ResourceManager.GetString("REST_Get_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/event-rest/{0}/events/?access_token={1}.
        /// </summary>
        internal static string REST_Get_Events {
            get {
                return ResourceManager.GetString("REST_Get_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/message-rest/me/events/{1}/messages?access_token={2}.
        /// </summary>
        internal static string REST_Get_Messages {
            get {
                return ResourceManager.GetString("REST_Get_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/spending-rest/me/events/{1}/moneyspendings?access_token={2}.
        /// </summary>
        internal static string REST_Get_MoneySpendings {
            get {
                return ResourceManager.GetString("REST_Get_MoneySpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/photo-rest/me/events/{1}/photos?access_token={2}.
        /// </summary>
        internal static string REST_Get_Photos {
            get {
                return ResourceManager.GetString("REST_Get_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/route-rest/me/events/{1}/routes?access_token={2}.
        /// </summary>
        internal static string REST_Get_Routes {
            get {
                return ResourceManager.GetString("REST_Get_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/trip-plan-rest/me/events/{0}/trip-plan?access_token={1}.
        /// </summary>
        internal static string REST_Get_TripPlan {
            get {
                return ResourceManager.GetString("REST_Get_TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/user-rest/me?access_token={0}.
        /// </summary>
        internal static string REST_Get_User {
            get {
                return ResourceManager.GetString("REST_Get_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/user-rest/me/settings?access_token={0}.
        /// </summary>
        internal static string REST_Get_User_Settings {
            get {
                return ResourceManager.GetString("REST_Get_User_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/oauth/token?grant_type=password&amp;client_id=utraveler-wp&amp;client_secret=utraveler_secret_code&amp;username={0}&amp;password={1}.
        /// </summary>
        internal static string REST_OAuth2_Token_Address {
            get {
                return ResourceManager.GetString("REST_OAuth2_Token_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/user-rest/register/UTRAVELER-WP.
        /// </summary>
        internal static string REST_Register_User {
            get {
                return ResourceManager.GetString("REST_Register_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/user-rest/requestResetPassword/{0}.
        /// </summary>
        internal static string REST_Request_Reset_Password {
            get {
                return ResourceManager.GetString("REST_Request_Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/event-rest/me/events/update?access_token={0}.
        /// </summary>
        internal static string REST_Update_Event {
            get {
                return ResourceManager.GetString("REST_Update_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/message-rest/me/events/{0}/messages/{1}/update?access_token={2}.
        /// </summary>
        internal static string REST_Update_Message {
            get {
                return ResourceManager.GetString("REST_Update_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/photo-rest/me/events/{0}/photos/{1}/update?access_token={2}.
        /// </summary>
        internal static string REST_Update_Photo {
            get {
                return ResourceManager.GetString("REST_Update_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/photo-rest/me/events/{0}/photos/update/many?access_token={1}.
        /// </summary>
        internal static string REST_Update_Photos {
            get {
                return ResourceManager.GetString("REST_Update_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/trip-plan-rest/me/events/{0}/trip-plan/update?access_token={1}.
        /// </summary>
        internal static string REST_Update_TripPlan {
            get {
                return ResourceManager.GetString("REST_Update_TripPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://utraveler.net/rest/user-rest/me/update?access_token={0}.
        /// </summary>
        internal static string REST_Update_User {
            get {
                return ResourceManager.GetString("REST_Update_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:8080/.
        /// </summary>
        internal static string RESTAddress {
            get {
                return ResourceManager.GetString("RESTAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utraveler-wp.
        /// </summary>
        internal static string RESTClientId {
            get {
                return ResourceManager.GetString("RESTClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utraveler_secret_code.
        /// </summary>
        internal static string RESTClientSecret {
            get {
                return ResourceManager.GetString("RESTClientSecret", resourceCulture);
            }
        }
    }
}
